//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PropertyAddressManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int Id { get; set; }
        public string StreetNumber { get; set; }
        public string Street { get; set; }
        public int SuburbId { get; set; }
        public int PostCode { get; set; }
        public int StateId { get; set; }
        public Nullable<int> UnitNumber { get; set; }
        public string PropertyType { get; set; }
        public string StreetType { get; set; }
    
        public virtual State State { get; set; }
        public virtual Suburb Suburb { get; set; }
    }
}
